2024-04-06 13:33:13,380 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:33:15,719 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:33:23,851 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:157]
2024-04-06 13:33:27,853 INFO: Processing update_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:185]
2024-04-06 13:33:49,776 INFO: Processing update_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:185]
2024-04-06 13:33:52,941 INFO: Processing get_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:223]
2024-04-06 13:33:58,328 INFO: Processing get_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:223]
2024-04-06 13:34:02,763 INFO: Processing delete_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:206]
2024-04-06 13:34:06,337 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:157]
2024-04-06 13:34:12,192 INFO: Processing analyze_text attempt [in /Users/saadiandishmand/Documents/home-test/app.py:100]
2024-04-06 13:34:16,797 INFO: Processing extract_entities_route attempt [in /Users/saadiandishmand/Documents/home-test/app.py:126]
2024-04-06 13:34:19,498 INFO: Processing detect_language_route attempt [in /Users/saadiandishmand/Documents/home-test/app.py:142]
2024-04-06 13:34:22,397 INFO: Processing login attempt [in /Users/saadiandishmand/Documents/home-test/app.py:80]
2024-04-06 13:34:27,165 INFO: Processing protected attempt [in /Users/saadiandishmand/Documents/home-test/app.py:92]
2024-04-06 13:35:02,410 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:37:41,284 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:37:49,088 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:37:53,579 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:38:22,462 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:39:00,103 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:39:03,015 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:39:03,059 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:157]
2024-04-06 13:40:42,989 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:40:46,845 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:40:46,925 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:157]
2024-04-06 13:42:35,409 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:42:37,862 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:43:03,302 INFO: Processing protected attempt [in /Users/saadiandishmand/Documents/home-test/app.py:92]
2024-04-06 13:43:04,289 INFO: Processing protected attempt [in /Users/saadiandishmand/Documents/home-test/app.py:92]
2024-04-06 13:43:16,075 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:157]
2024-04-06 13:44:01,084 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:44:11,959 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:44:15,647 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:44:31,742 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:45:15,613 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:51:08,496 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:51:10,871 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:53:41,435 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:54:07,992 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:54:10,319 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:54:45,356 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:157]
2024-04-06 13:58:32,419 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:37]
2024-04-06 13:58:39,253 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:40]
2024-04-06 13:58:43,085 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:39]
2024-04-06 13:58:52,018 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:39]
2024-04-06 13:59:49,219 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 13:59:51,600 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 13:59:56,786 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:153]
2024-04-06 14:00:01,980 INFO: Processing update_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:180]
2024-04-06 14:00:01,989 ERROR: 404 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /Users/saadiandishmand/Documents/home-test/app.py:232]
2024-04-06 14:00:05,555 INFO: Processing update_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:180]
2024-04-06 14:00:05,557 ERROR: 404 Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /Users/saadiandishmand/Documents/home-test/app.py:232]
2024-04-06 14:00:16,686 INFO: Processing update_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:180]
2024-04-06 14:00:29,403 INFO: Processing get_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:216]
2024-04-06 14:00:32,705 INFO: Processing extract_entities_route attempt [in /Users/saadiandishmand/Documents/home-test/app.py:124]
2024-04-06 14:00:35,172 INFO: Processing detect_language_route attempt [in /Users/saadiandishmand/Documents/home-test/app.py:139]
2024-04-06 14:00:37,737 INFO: Processing analyze_text attempt [in /Users/saadiandishmand/Documents/home-test/app.py:99]
2024-04-06 14:01:26,639 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:01:28,919 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:01:32,053 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:01:32,105 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:153]
2024-04-06 14:02:50,530 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:06:14,668 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:06:14,705 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:153]
2024-04-06 14:09:37,329 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:09:37,423 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:153]
2024-04-06 14:09:37,546 INFO: Processing login attempt [in /Users/saadiandishmand/Documents/home-test/app.py:80]
2024-04-06 14:09:37,645 INFO: Processing login attempt [in /Users/saadiandishmand/Documents/home-test/app.py:80]
2024-04-06 14:10:42,717 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:10:42,799 INFO: Processing create_user attempt [in /Users/saadiandishmand/Documents/home-test/app.py:153]
2024-04-06 14:10:42,941 INFO: Processing login attempt [in /Users/saadiandishmand/Documents/home-test/app.py:80]
2024-04-06 14:10:43,039 INFO: Processing login attempt [in /Users/saadiandishmand/Documents/home-test/app.py:80]
2024-04-06 14:10:43,044 INFO: Processing login attempt [in /Users/saadiandishmand/Documents/home-test/app.py:80]
2024-04-06 14:10:43,141 INFO: Processing protected attempt [in /Users/saadiandishmand/Documents/home-test/app.py:92]
2024-04-06 14:11:09,663 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:11:12,176 INFO: Flask application startup [in /Users/saadiandishmand/Documents/home-test/app.py:38]
2024-04-06 14:12:09,457 INFO: Processing analyze_text attempt [in /Users/saadiandishmand/Documents/home-test/app.py:99]
